<?php

namespace Proxies\__CG__\EPlan\PlanningBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Grille extends \EPlan\PlanningBundle\Entity\Grille implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Grille' . "\0" . 'id', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Grille' . "\0" . 'titre', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Grille' . "\0" . 'numeroSemestre', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Grille' . "\0" . 'etape', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Grille' . "\0" . 'ueGrilles');
        }

        return array('__isInitialized__', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Grille' . "\0" . 'id', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Grille' . "\0" . 'titre', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Grille' . "\0" . 'numeroSemestre', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Grille' . "\0" . 'etape', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Grille' . "\0" . 'ueGrilles');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Grille $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtape(\EPlan\PlanningBundle\Entity\Etape $etape)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtape', array($etape));

        return parent::setEtape($etape);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtape()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtape', array());

        return parent::getEtape();
    }

    /**
     * {@inheritDoc}
     */
    public function addUeGrille(\EPlan\PlanningBundle\Entity\UEGrille $ueGrille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUeGrille', array($ueGrille));

        return parent::addUeGrille($ueGrille);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUeGrille(\EPlan\PlanningBundle\Entity\UEGrille $ueGrille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUeGrille', array($ueGrille));

        return parent::removeUeGrille($ueGrille);
    }

    /**
     * {@inheritDoc}
     */
    public function getUeGrilles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUeGrilles', array());

        return parent::getUeGrilles();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroSemestre($numeroSemestre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroSemestre', array($numeroSemestre));

        return parent::setNumeroSemestre($numeroSemestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroSemestre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroSemestre', array());

        return parent::getNumeroSemestre();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreUes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreUes', array());

        return parent::getNombreUes();
    }

}
