<?php

namespace Proxies\__CG__\EPlan\PlanningBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Departement extends \EPlan\PlanningBundle\Entity\Departement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Departement' . "\0" . 'id', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Departement' . "\0" . 'nom', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Departement' . "\0" . 'mentions', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Departement' . "\0" . 'enseignants', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Departement' . "\0" . 'ecs');
        }

        return array('__isInitialized__', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Departement' . "\0" . 'id', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Departement' . "\0" . 'nom', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Departement' . "\0" . 'mentions', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Departement' . "\0" . 'enseignants', '' . "\0" . 'EPlan\\PlanningBundle\\Entity\\Departement' . "\0" . 'ecs');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Departement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function addMention(\EPlan\PlanningBundle\Entity\Mention $mentions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMention', array($mentions));

        return parent::addMention($mentions);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMention(\EPlan\PlanningBundle\Entity\Mention $mentions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMention', array($mentions));

        return parent::removeMention($mentions);
    }

    /**
     * {@inheritDoc}
     */
    public function getMentions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMentions', array());

        return parent::getMentions();
    }

    /**
     * {@inheritDoc}
     */
    public function getParcourtTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParcourtTypes', array());

        return parent::getParcourtTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreDeMention()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreDeMention', array());

        return parent::getNombreDeMention();
    }

    /**
     * {@inheritDoc}
     */
    public function addEc(\EPlan\PlanningBundle\Entity\Ec $ec)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEc', array($ec));

        return parent::addEc($ec);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEc(\EPlan\PlanningBundle\Entity\Ec $ec)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEc', array($ec));

        return parent::removeEc($ec);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcs', array());

        return parent::getEcs();
    }

    /**
     * {@inheritDoc}
     */
    public function addEnseignant(\EPlan\PlanningBundle\Entity\Enseignant $enseignant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEnseignant', array($enseignant));

        return parent::addEnseignant($enseignant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEnseignant(\EPlan\PlanningBundle\Entity\Enseignant $enseignant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEnseignant', array($enseignant));

        return parent::removeEnseignant($enseignant);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnseignants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnseignants', array());

        return parent::getEnseignants();
    }

}
