<?php

namespace EPlan\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends EntityRepository
{
    public function findWithMentions() {
        $qb = $this->createQueryBuilder('d')->join('d.mentions', 'm')->addSelect('m');
        return $qb->getQuery()->getResult();
    }
    public function findAndGetWithAll() {
        
    }
}
