<?php

namespace EPlan\PlanningBundle\Entity;

/**
 * EcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcRepository extends \Doctrine\ORM\EntityRepository
{
}
