<?php

namespace EPlan\PlanningBundle\Entity;

/**
 * EcUeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcUeRepository extends \Doctrine\ORM\EntityRepository
{
}
