<?php

namespace EPlan\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnseignantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignantRepository extends EntityRepository
{
    
    
    public function findByNomOrPrenom($critere)
{

  $qb = $this->createQueryBuilder('ens');
  $qb->where('ens.nom LIKE :nom OR ens.prenom LIKE :nom')
   ->orderBy('ens.nom', 'ASC')
   ->setParameter('nom', '%'.$critere.'%');
   return $qb->getQuery()
            ->getResult();
}
    
    
}
