<?php

namespace EPlan\PlanningBundle\Entity;

/**
 * GrilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrilleRepository extends \Doctrine\ORM\EntityRepository
{
}
