<?php

namespace EPlan\PlanningBundle\Entity;

/**
 * GrilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrilleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneWithUeGrilles($id) {
        $qb = $this->createQueryBuilder('g')->join('g.ueGrilles', 'u')->addSelect('u')->andWhere('d.id = :id')->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
}
