<?php

namespace EPlan\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MentionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentionRepository extends EntityRepository
{
    public function findWithDepartement() {
        $qb = $this->createQueryBuilder('m')->join('m.departement', 'd')->addSelect('d');
        return $qb->getQuery()->getSingleResult();
    }
    
    public function findWithParcourtTypes() {
        $qb = $this->createQueryBuilder('m')->join('m.parcourtTypes', 'p')->addSelect('p');
        return $qb->getQuery()->getResult();
    }
}
