<?php

namespace EPlan\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParcourtTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcourtTypeRepository extends EntityRepository
{
}
