<?php

namespace EPlan\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParcourtTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcourtTypeRepository extends EntityRepository
{
    public function findWithMention() {
        $qb = $this->createQueryBuilder('p')->join('p.mention', 'm')->addSelect('m');
        return $qb->getQuery()->getSingleResult();
    }
    
    public function findWithEtapes() {
        $qb = $this->createQueryBuilder('p')->join('p.etapes', 'e')->addSelect('e');
        return $qb->getQuery()->getResult();
    }
}
