<?php

namespace EPlan\PlanningBundle\Entity;

/**
 * UEGrilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UEGrilleRepository extends \Doctrine\ORM\EntityRepository
{
}
