e_plan_planning_manage_division:
    path:     /manageDivision
    defaults: { _controller: EPlanPlanningBundle:Division:managePresentation }
e_plan_planning_load_division:
    path:     /charger-les-departements
    defaults: { _controller: EPlanPlanningBundle:Division:loadDepartement }
e_plan_planning_registrer_parcourt_type:
    path:     /formCreateParcourtType
    defaults: { _controller: EPlanPlanningBundle:ParcourtType:formView }
e_plan_planning_registrer_enseignant:
    path:     /Creer-un-Enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:createEnseignant }
e_plan_planning_consult_enseignant:
    path:     /Consulter-un-Enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:consultEnseignant }
e_plan_planning_index_enseignant:
    path:     /
    defaults: { _controller: EPlanPlanningBundle:Enseignant:indexEnseignant }
e_plan_planning_attrib_ec_enseignant:
    path:     /attrib-ec-enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:attribEcEnseignant }
<<<<<<< HEAD
e_plan_planning_indexPlanManuel:
    path:     /param-plan-manuel
    defaults: { _controller: EPlanPlanningBundle:PlanManuel:indexPlanManuel }
e_plan_planning_test:
    path:     /param-plan-manuel-gpe
    defaults: { _controller: EPlanPlanningBundle:PlanManuel:gpePlanManuel }
    
=======
e_plan_planning_welcome:
    path:     /welcome
    defaults: { _controller: EPlanPlanningBundle:Presentation:welcome }

>>>>>>> aa0b05b072db46d2f39ba1fea9d611a49b364e91
