e_plan_planning_manage_division:
    path:     /manageDivision
    defaults: { _controller: EPlanPlanningBundle:Division:managePresentation }
e_plan_planning_show_one_grille:
    path:     /showGrille/{id}
    defaults: { _controller: EPlanPlanningBundle:Division:viewGrille }
    requirements:
        id:    \d+
e_plan_planning_generate_pdf_grille:
    path:     /pdfGrille/{id}
    defaults: { _controller: EPlanPlanningBundle:Division:pdfGrille }
    requirements:
        id:    \d+
e_plan_planning_send_link_grille:
    path:     /sendLinkGrille/{id}
    defaults: { _controller: EPlanPlanningBundle:Division:sendLinkGrille }
    requirements:
        id:    \d+
e_plan_planning_edit_one_grille:
    path:     /editOneGrille/{id}
    defaults: { _controller: EPlanPlanningBundle:Division:editOneGrille, id: 0 }
    requirements:
        id:    \d+
e_plan_planning_register_one_grille:
    path:     /registertOneGrille/{id}
    defaults: { _controller: EPlanPlanningBundle:Division:registerOneGrille }
    requirements:
        id:    \d+
e_plan_planning_load_division:
    path:     /charger-les-departements
    defaults: { _controller: EPlanPlanningBundle:Division:loadDepartement }
e_plan_planning_registrer_parcourt_type:
    path:     /formCreateParcourtType
    defaults: { _controller: EPlanPlanningBundle:ParcourtType:formView }
e_plan_planning_registrer_enseignant:
    path:     /Creer-un-Enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:createEnseignant }
e_plan_planning_consult_enseignant:
    path:     /Consulter-un-Enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:consultEnseignant }
e_plan_planning_index_enseignant:
    path:     /
    defaults: { _controller: EPlanPlanningBundle:Enseignant:indexEnseignant }
e_plan_planning_attrib_ec_enseignant:
    path:     /attrib-ec-enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:attribEcEnseignant }
e_plan_planning_fiche_enseignant:
    path:     /fiche-enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:ficheEnseignant }
e_plan_planning_ec_enseignant:
    path:     /alloc-enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:attribEc }
e_plan_planning_supp_enseignant:
    path:     /supp-enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:suppEnseignant }
e_plan_planning_suppec_enseignant:
    path:     /supp-ec-enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:suppEcEnseignant }
e_plan_planning_indexPlanManuel:
    path:     /param-plan-manuel
    defaults: { _controller: EPlanPlanningBundle:PlanManuel:indexPlanManuel }
e_plan_planning_test:
    path:     /param-plan-manuel-gpe
    defaults: { _controller: EPlanPlanningBundle:PlanManuel:gpePlanManuel }
e_plan_planning_welcome:
    path:     /welcome
    defaults: { _controller: EPlanPlanningBundle:Presentation:welcome }
e_plan_planning_view_parcourt_Type:
    path:     /viewParcourtType/{id}
    defaults: { _controller: EPlanPlanningBundle:Division:viewParcourtType }
    requirements:
        id:    \d+
e_plan_planning_mention_ec:
    path:     /param-plan-manuel-listEc
    defaults: { _controller: EPlanPlanningBundle:PlanManuel:ecMention }
e_plan_planning_modif_enseignant:
    path:     /modif-enseignant
    defaults: { _controller: EPlanPlanningBundle:Enseignant:modifEnseignant }
e_plan_planning_registrer_salle:
     path:     /formCreateSalle
     defaults: { _controller: EPlanPlanningBundle:Salle:salle }
e_plan_planning_register_disponibilite:
     path:     /SalleDispo
     defaults: { _controller: EPlanPlanningBundle:SalleDispo:SalleDisponible }
e_plan_planning_register_indisponibilite:
     path:     /SalleIndispo
     defaults: { _controller: EPlanPlanningBundle:SalleDispo:Salleindisponible }	
e_plan_planning_view_parcourt_Type:
    path:     /viewParcourtType/{id}
    defaults: { _controller: EPlanPlanningBundle:Division:viewParcourtType }
    requirements:
        id:    \d+
    defaults: { _controller: EPlanPlanningBundle:Enseignant:modifEnseignant }

e_plan_planning_enregitrer_UE:
    path:     /enregUE
    defaults: { _controller: EPlanPlanningBundle:Division:enregistrerUE }
    
e_plan_planning_enregitrer_Ec:
    path:     /enregEc
    defaults: { _controller: EPlanPlanningBundle:Division:enregistrerEc }
