parameters:
#    e_plan_planning.example.class: EPlan\PlanningBundle\Example

services:
#    e_plan_planning.example:
#        class: %e_plan_planning.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
